vim.api.nvim_create_user_command("T", function()
    vim.cmd("split")
    vim.cmd("wincmd j")
    vim.cmd("resize 15")
    vim.cmd("term")
end, { nargs = 0 })

vim.api.nvim_create_user_command("TT", function()
    vim.cmd("split")
    vim.cmd("wincmd j")
    vim.cmd("resize 15")

    vim.cmd("wincmd v")
    vim.cmd("wincmd l")
    vim.cmd("term")
    vim.cmd("stopinsert")

    vim.cmd("wincmd h")
    vim.cmd("term")
end, { nargs = 0 })

vim.api.nvim_create_user_command("Note", function()
    vim.cmd("vsplit")
    vim.cmd("wincmd l")
    vim.cmd("e ~/nvim-note.md")
end, { nargs = 0 })
